In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/household_power_consumption.txt",
    sep=';',
    low_memory=False,
    na_values='?'
)

print(df.head())
print(df.shape)

         Date      Time  Global_active_power  Global_reactive_power  Voltage  \
0  16/12/2006  17:24:00                4.216                  0.418   234.84
1  16/12/2006  17:25:00                5.360                  0.436   233.63
2  16/12/2006  17:26:00                5.374                  0.498   233.29
3  16/12/2006  17:27:00                5.388                  0.502   233.74
4  16/12/2006  17:28:00                3.666                  0.528   235.68

   Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3
0              18.4             0.0             1.0            17.0
1              23.0             0.0             1.0            16.0
2              23.0             0.0             2.0            17.0
3              23.0             0.0             1.0            17.0
4              15.8             0.0             1.0            17.0
(2075259, 9)

In [3]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [4]:
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])
df.drop(columns=['Date', 'Time'], inplace=True)
df.set_index('Datetime', inplace=True)

In [6]:
df.isnull().sum()

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [7]:
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [8]:
df = df.sort_index()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2075259 entries, 2006-12-16 17:24:00 to 2010-11-26 21:02:00
Data columns (total 7 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Global_active_power    float64
 1   Global_reactive_power  float64
 2   Voltage                float64
 3   Global_intensity       float64
 4   Sub_metering_1         float64
 5   Sub_metering_2         float64
 6   Sub_metering_3         float64
dtypes: float64(7)
memory usage: 126.7 MB

In [10]:
df["Sub_metering_1"].value_counts()

Sub_metering_1
0.0     1880175
1.0       84936
2.0       19017
38.0      16119
37.0      14892
         ...
82.0          3
88.0          3
87.0          3
84.0          2
86.0          2
Name: count, Length: 88, dtype: int64

In [11]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [12]:
df.isnull().sum()

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [13]:
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [14]:
daily_df = df.resample('D').sum()
print(daily_df.head())

            Global_active_power  Global_reactive_power    Voltage  \
Datetime
2006-12-16             1209.176                 34.922   93552.53
2006-12-17             3390.460                226.006  345725.32
2006-12-18             2203.826                161.792  347373.64
2006-12-19             1666.194                150.942  348479.01
2006-12-20             2225.748                160.998  348923.61

            Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3
Datetime
2006-12-16            5180.8             0.0           546.0          4926.0
2006-12-17           14398.6          2033.0          4187.0         13341.0
2006-12-18            9247.2          1063.0          2621.0         14018.0
2006-12-19            7094.0           839.0          7602.0          6197.0
2006-12-20            9313.0             0.0          2648.0         14063.0

In [15]:
monthly_df = df.resample('M').sum()
print(monthly_df.head())

            Global_active_power  Global_reactive_power      Voltage  \
Datetime
2006-12-31            41813.282               2889.436   5309773.22
2007-01-31            69011.862               5922.396  10753521.91
2007-02-28            56488.886               4581.608   9697260.78
2007-03-31            58862.192               5122.184  10736280.75
2007-04-30            35181.466               4688.994   9450794.83

            Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3
Datetime
2006-12-31          176594.8         27460.0         48712.0        162951.0
2007-01-31          292241.2         56433.0         79274.0        329578.0
2007-02-28          238463.6         47584.0         64604.0        270274.0
2007-03-31          248772.2         60769.0        104762.0        290361.0
2007-04-30          151026.2         42078.0         38417.0        189503.0

In [16]:
monthly_df.shape

(48, 7)

In [17]:
monthly_df.to_csv("monthly_data.csv")